Lecture 110: Convergence in Repeated Matrix Multiplication (Pre-requisite 1)

In [1]:
import numpy 

A=numpy.mat('1 2;3 4')

v=numpy.mat('1;1')

print(A*v)


[[3]
 [7]]


In [4]:
import numpy 

A=numpy.mat('1 2;3 4')

v=numpy.mat('1;1')

print(v)

print('######################################')

for i in range(10):
    z=A*v
    z=z/numpy.linalg.norm(z)
    print(z)
    v=z
    print('********************************')


[[1]
 [1]]
######################################
[[0.3939193 ]
 [0.91914503]]
********************************
[[0.41750017]
 [0.90867684]]
********************************
[[0.41586776]
 [0.9094251 ]]
********************************
[[0.41598089]
 [0.90937336]]
********************************
[[0.41597305]
 [0.90937694]]
********************************
[[0.41597359]
 [0.90937669]]
********************************
[[0.41597356]
 [0.90937671]]
********************************
[[0.41597356]
 [0.90937671]]
********************************
[[0.41597356]
 [0.90937671]]
********************************
[[0.41597356]
 [0.90937671]]
********************************
